stages:
- name: ReleaseBuild
  steps:
  - publishImageConfig:
      dockerfilePath: ./Container.Deployed.Test/Dockerfile
      buildContext: .
      tag: release
      registry: localhost:5000
- name: Release
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
timeout: 60
notification: {}
